In [1]:
import numpy as np

In [2]:
np.random.choice(5, size=5, replace=False)

array([0, 4, 1, 2, 3])

In [8]:
q = np.random.randint(0, (2 ** 5) / 5, size=(5,))
q

array([5, 2, 0, 5, 0])

In [9]:
public_key = 2

In [10]:
s = public_key * q
s

array([10,  4,  0, 10,  0])

In [11]:
r = np.random.randint(1 - (2 ** 5), 2 ** 5, size=5)
r

array([-18,   3,  -9, -21, -13])

In [12]:
public_key * q + r

array([ -8,   7,  -9, -11, -13])

In [11]:
import random

num_bits = 1024
x = random.randrange(2 ** (num_bits - 1), 2 ** num_bits) | 1
x

103299713675969608698749810522951005423872674573477956696781072525267261940181815125259189423930142236716389033545602041972829419267544156335896132938915431786317629558735485059784424756219451641543361560804351200766049881974520479377524806620534511003424155925517937661798282904764472583496684569213295022927

In [12]:
type(x)

int

In [31]:
import random
import numpy as np

num_bits = 3
x = np.fromfunction(lambda i, j: i + j, shape=(2,2))
x, type(x)

(array([[0., 1.],
        [1., 2.]]),
 numpy.ndarray)

In [20]:
np.fromfunction(lambda i, j: i, (2, 2), dtype=float)

array([[0., 0.],
       [1., 1.]])

In [52]:
num_bits = 1024
x = np.array([random.randrange(2 ** (num_bits - 1), 2 ** num_bits) for _ in range(4)], dtype=object)
x, x.dtype

(array([175133772148423773940758709660138124097840033979051867659059667729729933771311118452219567933372667359203757869627299772321450454449810411317005347479473443167544780702677881008844759949433657758013665011371542647612134950743377265719242905305875870918942404183974672027068772574353278611780342926179674843685,
        122433682823174711450462525879979572490085205063337907526813723447417480777146799473914968932835847378401264742361738790392682383131978713340357380634690794256067949010768017373006671849033017824879522624149618864318998296825555155175410562545784431140253144015416450247501490489542832867413473324361742972290,
        93529720460867025185183787731330024447334679503266073653541544043428253762258270133157905862848240668812242245954706886277776011974727910834295271661276276223247932078240312590730951385462287343031611730376780475249306431634056248926380232630090609068016491154674186535555283125834472766821438473756203859990,
        932143774202807715137342887450161258

In [54]:
type(x[0])

int

In [57]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [58]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [62]:
b = 4
trials = 100

for _ in range(trials):
    print(random.randrange(2 ** (b - 1) + 1, 2 ** b, 2))

13
15
9
15
13
9
13
15
15
15
15
9
15
9
15
9
9
9
9
9
11
11
9
15
9
11
11
11
13
9
11
15
9
13
9
15
11
13
15
9
11
11
13
15
13
9
13
13
11
11
13
13
9
9
15
11
15
9
15
11
13
15
13
13
13
15
9
11
15
11
15
11
11
9
9
9
11
15
9
11
11
15
13
13
9
9
11
15
13
15
9
11
13
13
11
13
13
13
15
15


In [ ]:
8, 9, 10, 11, 12, 13, 14, 15, 16

In [63]:
type(9) is int

True

In [1]:
1 - 2 ** 10, 2 **10

(-1023, 1024)

In [19]:
import random
random.randrange(-1024, 1024, 2)

840