In [1]:
import numpy as np

In [2]:
np.random.choice(5, size=5, replace=False)

array([0, 4, 1, 2, 3])

In [8]:
q = np.random.randint(0, (2 ** 5) / 5, size=(5,))
q

array([5, 2, 0, 5, 0])

In [9]:
public_key = 2

In [10]:
s = public_key * q
s

array([10,  4,  0, 10,  0])

In [11]:
r = np.random.randint(1 - (2 ** 5), 2 ** 5, size=5)
r

array([-18,   3,  -9, -21, -13])

In [12]:
public_key * q + r

array([ -8,   7,  -9, -11, -13])