In [7]:
import random
import math
import numpy as np

#### Parameters

In [5]:
security = 3
gamma = security ** 5
eta = security ** 2
rho = security
rho_prime = 2 * security
tau = gamma + security

#### Key

In [23]:
def private_key(num_bits: int) -> int:
    key = np.random.randint(2 ** (num_bits - 1), 2 ** num_bits)
    while key % 2 != 1:
        key = np.random.randint(2 ** (num_bits - 1), 2 ** num_bits)
    return key
        
def public_key(private_key: int,
               size: int) -> int:
    key = np.empty(shape=(size,), dtype=np.int64)
    for _ in range(size):
        
    return key, largest

In [69]:
np.empty(shape=(3,), dtype=int)

array([4616981938510815294, 4613349226564724111, 4612217596255138984])

In [27]:
private_key(eta)

89

In [71]:
np.random.randint(0, 100, size=5)

array([70, 22, 84, 46, 59])

In [72]:
np.random.randint(0, 100, size=(5,))

array([66, 10, 22, 81, 82])

In [75]:
np.random.randint(0, 100, 5)

array([63, 37, 48, 55, 69])

In [76]:
np.empty(shape=5, dtype=int)

array([0, 0, 0, 0, 0])

array([0, 0, 1, 1, 1])

In [100]:
i = np.random.choice([True, False], size=5)
x = np.arange(5)
x, i, x[i]

(array([0, 1, 2, 3, 4]),
 array([False,  True,  True,  True, False]),
 array([1, 2, 3]))

In [4]:
message = 0b1001
message

9

In [5]:
x = 9
x

9

In [6]:
bin(9)

'0b1001'

In [11]:
bin(0b1001)[2:]

'1001'

In [13]:
import numpy as np
np.array([int(i) for i in bin(0b1001)[2:]])

array([1, 0, 0, 1])

In [20]:
decimal_number = 42

# Convert decimal to binary string
binary_string = bin(decimal_number)[2:]

# Convert binary string to NumPy array of integers
binary_array = np.array(list(map(int, binary_string)))
binary_array

array([1, 0, 1, 0, 1, 0])

In [15]:
bin(42)

'0b101010'

In [16]:
d = np.array([1,2,3,4,5])
m = 8
((d[:,None] & (1 << np.arange(m))) > 0).astype(int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0]])

In [17]:
d[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
1 << np.arange(m)

array([  1,   2,   4,   8,  16,  32,  64, 128])

In [19]:
d[:, None] & (1 << np.arange(m))

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [1, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0],
       [1, 0, 4, 0, 0, 0, 0, 0]])

In [21]:
x = np.arange(9)
x, x % 2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 0, 1, 0, 1, 0, 1, 0]))

In [22]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
A = np.arange(3)
n = 5

In [25]:
random_indices = np.random.choice(len(A), (n, len(A)), replace=True)
random_indices

array([[0, 1, 1],
       [2, 2, 1],
       [1, 2, 2],
       [1, 2, 0],
       [0, 2, 2]])

In [26]:
subset_masks = np.eye(len(A))[random_indices]
subset_masks

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.]],

       [[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.]]])

In [27]:
subset_sums = np.dot(subset_masks, A)
subset_sums

array([[0., 1., 1.],
       [2., 2., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 2., 2.]])

In [24]:

# Create a mask for the selected elements in each subset

# Calculate the sum of each subset using matrix multiplication


array([[1., 0., 2.],
       [0., 1., 0.],
       [1., 0., 2.],
       [2., 0., 1.],
       [0., 2., 2.]])

In [30]:
x = np.arange(3)
i = np.random.choice([0, 1], size=(5, 3))
x, i, i @ x

(array([0, 1, 2]),
 array([[0, 0, 1],
        [1, 0, 1],
        [1, 1, 0],
        [1, 1, 1],
        [1, 0, 0]]),
 array([2, 2, 1, 3, 0]))

In [31]:
binary_array = np.random.choice([0,1], size=5)
binary_array

array([1, 1, 1, 0, 0])

In [32]:
binary_string = ''.join(map(str, binary_array))
binary_string

'11100'

In [33]:
decimal_int = int(binary_string, 2)
decimal_int

28