In [7]:
import random
import math
import numpy as np

#### Parameters

In [5]:
security = 3
gamma = security ** 5
eta = security ** 2
rho = security
rho_prime = 2 * security
tau = gamma + security

#### Key

In [23]:
def private_key(num_bits: int) -> int:
    key = np.random.randint(2 ** (num_bits - 1), 2 ** num_bits)
    while key % 2 != 1:
        key = np.random.randint(2 ** (num_bits - 1), 2 ** num_bits)
    return key
        
def public_key(private_key: int,
               size: int) -> int:
    key = np.empty(shape=(size,), dtype=np.int64)
    for _ in range(size):
        
    return key, largest

In [69]:
np.empty(shape=(3,), dtype=int)

array([4616981938510815294, 4613349226564724111, 4612217596255138984])

In [27]:
private_key(eta)

89

In [71]:
np.random.randint(0, 100, size=5)

array([70, 22, 84, 46, 59])

In [72]:
np.random.randint(0, 100, size=(5,))

array([66, 10, 22, 81, 82])

In [75]:
np.random.randint(0, 100, 5)

array([63, 37, 48, 55, 69])

In [76]:
np.empty(shape=5, dtype=int)

array([0, 0, 0, 0, 0])

array([0, 0, 1, 1, 1])

In [100]:
i = np.random.choice([True, False], size=5)
x = np.arange(5)
x, i, x[i]

(array([0, 1, 2, 3, 4]),
 array([False,  True,  True,  True, False]),
 array([1, 2, 3]))

array([1, 3])

array([False,  True,  True,  True, False])